service: portfoliobackend

frameworkVersion: '>=1.28.0 <2.0.0'

provider:
  name: aws
  runtime: go1.x

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  profile:
    handler: bin/profile
    events:
      - http:
          path: profile
          method: get