# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build-backend:
    docker:
      - image: circleci/python:3.7.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Backend/requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r Backend/requirements.txt
            pip install -U moto
            pip install -U pytest
            pip install -U coveralls            

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "Backend/requirements.txt" }}

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pytest Backend
            coveralls

      - persist_to_workspace:
          root: .
          paths:
            - Backend

  build-frontend:
    docker:
      - image: circleci/node:8.10

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: |
            sudo npm install -g gatsby-cli
            cd Frontend && npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-

      - run:
          name: Build Site
          command: cd Frontend && gatsby build

      - persist_to_workspace:
          root: .
          paths:
            - Frontend

  deploy-frontend:
    docker:
      - image: circleci/node:8.10
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Deploy frontend to aws
          command: cd Frontend && npm run publish

  deploy-backend:
    docker:
      - image: circleci/node:8.10
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Install dependencies
          command: |
            cd Backend && npm install
            sudo npm install -g serverless       
      - run:
          name: Deploy backend to aws
          command: cd Backend && sudo serverless deploy

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-backend
      - build-frontend
      - deploy-frontend:
          requires:
            - build-frontend
          filters:
            branches:
              only: master
      - deploy-backend:
          requires:
            - build-backend
          filters:
            branches:
              only: master
