# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build-backend:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.7.4

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Backend/requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r Backend/requirements.txt
            pip install -U moto
            pip install -U pytest

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "Backend/requirements.txt" }}

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pytest Backend

  build-frontend:
    docker:
      - image: circleci/node:8.10

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: |
            npm install -g gatsby-cli
            cd Frontend && npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-

      # run tests!
      - run:
          name: Build Site
          command: cd Frontend && gatsby build

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-backend
      - build-frontend
